apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: custom-spring
  title: Test for custom Spring template
  description: Description for custom Spring template
spec:
  owner: kusharata
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: write-to-file
      name: Custom Write to File Test
      action: custom
      input:
        contents: 'asd'
        filename: 'somefile'

    #- id: fetch-docs
      #name: Fetch Docs
      #action: fetch:plain
      #input:
        #targetPath: ./community
        #url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    #- id: publish
      #name: Publish
      #action: publish:github
      #input:
        #allowedHosts: ['github.com']
        #description: 'This is {{ parameters.name }}'
        #repoUrl: '{{ parameters.repoUrl }}'

    #- id: register
      #name: Register
      #action: catalog:register
      #input:
        #repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        #catalogInfoPath: '/catalog-info.yaml'

#  output:
#    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
#    entityRef: '{{ steps.register.output.entityRef }}'